sudo: false
cache: bundler
language: ruby
script: bundle exec rake ci
rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0 --server -Xcompile.invokedynamic=false'
    - rvm: jruby-head
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
  allow_failures:
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: 1.9.3
    - rvm: 1.9.2
    - rvm: 1.8.7
  fast_finish: true
branches:
  only:
    - master
